title: Niels Lommers # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist/Machine Learning Engineer
  <br><p style="text-align: justify;">I am a dedicated Mechanical Engineer with a passion for mathematics, machine learning, data science, and IoT. I thrive on creating efficient and pragmatic solutions and enjoy constantly innovating and learning new techniques with a team, and sharing this knowledge with others.</p><br>

  <a href="https://www.linkedin.com/in/nielslommers/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
